CREATE TABLE `staff` (
	`STAFF_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`STAFF_NAME` VARCHAR(50) NULL DEFAULT NULL,
	`STAFF_SEX` ENUM('男','女') NULL DEFAULT '男',
	`STAFF_AGE` TINYINT(4) NULL DEFAULT NULL,
	PRIMARY KEY (`STAFF_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;